name: NestJS CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  setup-env:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}

    steps:
      - name: Add DB_URL key to env
        run: echo "DB_URL=$DB_URL" > .env
      - name: Add DB_HOST key to env
        run: echo "DB_HOST=$DB_HOST" >> .env
      - name: Add DB_PORT key to env
        run: echo "DB_PORT=$DB_PORT" >> .env
      - name: Add DB_DATABASE key to env
        run: echo "DB_DATABASE=$DB_DATABASE" >> .env
      - name: Add DB_USERNAME key to env
        run: echo "DB_USERNAME=$DB_USERNAME" >> .env
      - name: Add DB_PASSWORD key to env
        run: echo "DB_PASSWORD=$DB_PASSWORD" >> .env
      - name: Add OPENAI_API_KEY key to env
        run: echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
      - name: Add FRONTEND_URL key to env
        run: echo "FRONTEND_URL=$FRONTEND_URL" >> .env
      - name: Add OPENAI_API_URL key to env
        run: echo "OPENAI_API_URL=$OPENAI_API_URL" >> .env
      - name: List files
        run: ls -al
      - name: Upload env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
  build:
    runs-on: ubuntu-latest
    needs: setup-env

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Download env file
        uses: actions/download-artifact@v4
        with:
          name: env-file
      - name: Display env file
        run: cat .env
      - run: npm install
      - run: npm run build --if-present
      - run: node dist/main.js
